// Builds factory-market/tutorial/levels.js — the intro tutorial's demo levels.
// Most reuse real working levels (lock one DGP alternative, toggle the veil);
// two are minimal hand-built levels. Re-run after editing:
//   node factory-market/tutorial/build.mjs   (from ollij.fi/)
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dir = dirname(fileURLToPath(import.meta.url));
const data = JSON.parse(readFileSync(join(__dir, '..', 'levels', 'export.json'), 'utf8'));
const getLevel = (id) => JSON.parse(JSON.stringify(data.levels.find(l => l.meta.id === id)));

function lock(level, altIndex, { unveil = false } = {}) {
    const sel = level.dgpAlternatives?.[altIndex];
    if (sel) {
        if (sel.components?.length) level.components = [...level.components, ...sel.components];
        if (sel.connections?.length) level.connections = [...(level.connections || []), ...sel.connections];
    }
    delete level.dgpAlternatives;
    if (unveil) level.veiledTiles = [];
    return level;
}

// A minimal sack → straight drop → one bin level, parameterised by plex (the
// conveyors + bin show balls in gray when plex is on).
function dropLevel(id, { plex = false } = {}) {
    return {
        meta: { id, title: id },
        grid: { width: 9, height: 8 },
        veiledTiles: [],
        components: [
            { id: 'sack', type: 'sack', position: { x: 4, y: 1 }, params: { label: 'sack', showContents: true, contents: { red: 50, blue: 30, green: 20 } } },
            { id: 'arm', type: 'arm', position: { x: 4, y: 2 }, params: { assignedSackId: null, outputConveyorId: null, varName: 'arm', id: 'arm', label: 'arm', drawCount: 1, plex } },
            { id: 'c1', type: 'conveyor', position: { x: 4, y: 3 }, params: { direction: 'down', speed: 1, plex } },
            { id: 'c2', type: 'conveyor', position: { x: 4, y: 4 }, params: { direction: 'down', speed: 1, plex } },
            { id: 'obs', type: 'observation', position: { x: 4, y: 5 }, params: { isPredictionTarget: true, observationIndex: 0, plex } },
        ],
        connections: [
            { from: 'sack', to: 'arm' }, { from: 'arm', to: 'c1' },
            { from: 'c1', to: 'c2' }, { from: 'c2', to: 'obs' },
        ],
        samplingSchedule: [{ armId: 'arm', armVarName: 'arm', time: 0 }],
        simulation: { ballProductionInterval: 3000, ballSpeed: 1, ballsToSpawn: 1, seed: 12345 },
    };
}

const STEPS = [
    {
        title: 'The sack draws at random',
        body: 'Every ball is drawn at random from the sack — here 50% red, 30% blue, 20% green, each draw independent. Watch the balls collect in the bin: their colours settle into those proportions. This randomness drives the whole game.',
        level: dropLevel('tut-sampling'),
    },
    {
        title: 'A mixer routes at random',
        body: 'A mixer sends each ball in a random direction, ignoring its colour. This one splits three ways with equal chance, so the three bins fill up about evenly.',
        level: lock(getLevel('level-3'), 0, { unveil: true }),
    },
    {
        title: 'A filter sorts by colour',
        body: 'A filter routes balls by colour — this one sends red left and every other colour right, the same way every time. So the split between the bins reflects how much red the sack holds.',
        level: lock(getLevel('level-13'), 0, { unveil: true }),
    },
    {
        title: 'Plexiglass hides a ball’s colour',
        body: 'Behind plexiglass you can still see the belt and that a ball is on it — but not its colour. The ball shows gray with a “?”. You’d have to work out the colours from how the factory behaves downstream.',
        level: dropLevel('tut-plex', { plex: true }),
    },
    {
        title: 'Hidden parts you must infer',
        body: 'And sometimes a whole part of the factory is hidden — you see balls go in and where they come out, but not the mechanism in between. Together with the other players, you infer it from those inputs and outputs. That is the game.',
        level: lock(getLevel('level-13'), 0, { unveil: false }),
    },
];

const out = `// AUTO-GENERATED by tutorial/build.mjs — do not edit by hand.
window.TUTORIAL_STEPS = ${JSON.stringify(STEPS, null, 1)};
`;
writeFileSync(join(__dir, 'levels.js'), out);
console.log(`wrote tutorial/levels.js (${STEPS.length} steps, ${(out.length / 1024).toFixed(1)} KB)`);
