// AUTO-GENERATED by tutorial/build.mjs — do not edit by hand.
window.TUTORIAL_STEPS = [
 {
  "title": "The sack draws at random",
  "body": "Every ball is drawn at random from the sack — here 50% red, 30% blue, 20% green, each draw independent. Watch the balls collect in the bin: their colours settle into those proportions. This randomness drives the whole game.",
  "level": {
   "meta": {
    "id": "tut-sampling",
    "title": "tut-sampling"
   },
   "grid": {
    "width": 9,
    "height": 8
   },
   "veiledTiles": [],
   "components": [
    {
     "id": "sack",
     "type": "sack",
     "position": {
      "x": 4,
      "y": 1
     },
     "params": {
      "label": "sack",
      "showContents": true,
      "contents": {
       "red": 50,
       "blue": 30,
       "green": 20
      }
     }
    },
    {
     "id": "arm",
     "type": "arm",
     "position": {
      "x": 4,
      "y": 2
     },
     "params": {
      "assignedSackId": null,
      "outputConveyorId": null,
      "varName": "arm",
      "id": "arm",
      "label": "arm",
      "drawCount": 1,
      "plex": false
     }
    },
    {
     "id": "c1",
     "type": "conveyor",
     "position": {
      "x": 4,
      "y": 3
     },
     "params": {
      "direction": "down",
      "speed": 1,
      "plex": false
     }
    },
    {
     "id": "c2",
     "type": "conveyor",
     "position": {
      "x": 4,
      "y": 4
     },
     "params": {
      "direction": "down",
      "speed": 1,
      "plex": false
     }
    },
    {
     "id": "obs",
     "type": "observation",
     "position": {
      "x": 4,
      "y": 5
     },
     "params": {
      "isPredictionTarget": true,
      "observationIndex": 0,
      "plex": false
     }
    }
   ],
   "connections": [
    {
     "from": "sack",
     "to": "arm"
    },
    {
     "from": "arm",
     "to": "c1"
    },
    {
     "from": "c1",
     "to": "c2"
    },
    {
     "from": "c2",
     "to": "obs"
    }
   ],
   "samplingSchedule": [
    {
     "armId": "arm",
     "armVarName": "arm",
     "time": 0
    }
   ],
   "simulation": {
    "ballProductionInterval": 3000,
    "ballSpeed": 1,
    "ballsToSpawn": 1,
    "seed": 12345
   }
  }
 },
 {
  "title": "A mixer routes at random",
  "body": "A mixer sends each ball in a random direction, ignoring its colour. This one splits three ways with equal chance, so the three bins fill up about evenly.",
  "level": {
   "meta": {
    "id": "level-3",
    "title": "Level 3",
    "description": "Testing from editor",
    "bettingConfig": {
     "granularity": 10
    }
   },
   "grid": {
    "width": 10,
    "height": 8
   },
   "veiledTiles": [],
   "components": [
    {
     "id": "comp1",
     "type": "sack",
     "position": {
      "x": 4,
      "y": 1
     },
     "params": {
      "label": "comp1",
      "showContents": true,
      "contents": {
       "red": 100
      }
     }
    },
    {
     "id": "comp2",
     "type": "conveyor",
     "position": {
      "x": 4,
      "y": 3
     },
     "params": {
      "direction": "down",
      "speed": 1,
      "plex": false
     }
    },
    {
     "id": "arm1",
     "type": "arm",
     "position": {
      "x": 4,
      "y": 2
     },
     "params": {
      "assignedSackId": null,
      "outputConveyorId": null,
      "varName": "arm1",
      "id": "arm1",
      "label": "arm1",
      "drawCount": 1
     }
    },
    {
     "id": "comp10",
     "type": "observation",
     "position": {
      "x": 4,
      "y": 6
     },
     "params": {
      "isPredictionTarget": false,
      "observationIndex": 1
     }
    },
    {
     "id": "comp12",
     "type": "observation",
     "position": {
      "x": 6,
      "y": 4
     },
     "params": {
      "isPredictionTarget": false,
      "observationIndex": 2
     }
    },
    {
     "id": "comp14",
     "type": "observation",
     "position": {
      "x": 2,
      "y": 4
     },
     "params": {
      "isPredictionTarget": false,
      "observationIndex": 0
     }
    },
    {
     "id": "comp8",
     "type": "splitter",
     "position": {
      "x": 4,
      "y": 4
     },
     "params": {
      "sides": {
       "up": {
        "type": "input"
       },
       "right": {
        "type": "output"
       },
       "down": {
        "type": "output"
       },
       "left": {
        "type": "output"
       }
      },
      "bounceDuration": 600,
      "plex": false
     }
    },
    {
     "id": "comp9",
     "type": "conveyor",
     "position": {
      "x": 4,
      "y": 5
     },
     "params": {
      "direction": "down",
      "speed": 1,
      "plex": false
     }
    },
    {
     "id": "comp11",
     "type": "conveyor",
     "position": {
      "x": 5,
      "y": 4
     },
     "params": {
      "direction": "right",
      "speed": 1,
      "plex": false
     }
    },
    {
     "id": "comp13",
     "type": "conveyor",
     "position": {
      "x": 3,
      "y": 4
     },
     "params": {
      "direction": "left",
      "speed": 1,
      "plex": false
     }
    }
   ],
   "connections": [
    {
     "from": "comp1",
     "to": "arm1"
    },
    {
     "from": "arm1",
     "to": "comp2"
    },
    {
     "from": "comp2",
     "to": "comp8"
    },
    {
     "from": "comp8",
     "to": "comp11"
    },
    {
     "from": "comp8",
     "to": "comp9"
    },
    {
     "from": "comp8",
     "to": "comp13"
    },
    {
     "from": "comp9",
     "to": "comp10"
    },
    {
     "from": "comp11",
     "to": "comp12"
    },
    {
     "from": "comp13",
     "to": "comp14"
    }
   ],
   "dgpScript": "\nsack(\"comp1\", {red: 100});\n\nconst arm1 = arm();\n\nschedule({\n  arm1: [0]\n});\n\npredict(\"dist\");\n\nmontecarlo(1000);",
   "dgpResult": {
    "sacks": {
     "comp1": {
      "label": "comp1",
      "contents": {
       "red": 100
      },
      "mode": "finite"
     }
    },
    "arms": {
     "arm1": {
      "id": "arm1",
      "varName": "arm1"
     }
    },
    "schedule": [
     {
      "armId": "arm1",
      "armVarName": "arm1",
      "time": 0
     }
    ],
    "questionText": "",
    "prediction": {
     "target": null,
     "what": "dist"
    },
    "buckets": null,
    "monteCarloSamples": 1000,
    "showFullDistribution": false,
    "fineGrainedDisplay": null,
    "disableBranching": false,
    "ballCount": 1
   },
   "samplingSchedule": [
    {
     "armId": "arm1",
     "armVarName": "arm1",
     "time": 0
    }
   ],
   "correctDistribution": {
    "A": 0.3333333333333333,
    "B": 0.3333333333333333,
    "C": 0.3333333333333333
   },
   "intendedModel": "",
   "simulation": {
    "ballProductionInterval": 3000,
    "ballSpeed": 1,
    "ballsToSpawn": 1,
    "seed": 1201856123
   }
  }
 },
 {
  "title": "A filter sorts by colour",
  "body": "A filter routes balls by colour — this one sends red left and every other colour right, the same way every time. So the split between the bins reflects how much red the sack holds.",
  "level": {
   "meta": {
    "id": "level-13",
    "title": "Level 13",
    "description": "Testing from editor",
    "bettingConfig": {
     "granularity": 10
    }
   },
   "grid": {
    "width": 10,
    "height": 8
   },
   "veiledTiles": [],
   "components": [
    {
     "id": "comp1",
     "type": "sack",
     "position": {
      "x": 4,
      "y": 1
     },
     "params": {
      "label": "comp1",
      "showContents": true,
      "contents": {
       "red": 50,
       "blue": 30,
       "green": 20
      }
     }
    },
    {
     "id": "comp2",
     "type": "conveyor",
     "position": {
      "x": 4,
      "y": 3
     },
     "params": {
      "direction": "down",
      "speed": 1,
      "plex": false
     }
    },
    {
     "id": "arm1",
     "type": "arm",
     "position": {
      "x": 4,
      "y": 2
     },
     "params": {
      "assignedSackId": null,
      "outputConveyorId": null,
      "varName": "arm1",
      "id": "arm1",
      "label": "arm1",
      "drawCount": 1
     }
    },
    {
     "id": "comp8",
     "type": "conveyor-turn",
     "position": {
      "x": 5,
      "y": 4
     },
     "params": {
      "turn": "right-to-down",
      "speed": 1,
      "plex": false
     }
    },
    {
     "id": "comp9",
     "type": "conveyor-turn",
     "position": {
      "x": 3,
      "y": 4
     },
     "params": {
      "turn": "left-to-down",
      "speed": 1,
      "plex": false
     }
    },
    {
     "id": "comp10",
     "type": "observation",
     "position": {
      "x": 3,
      "y": 5
     },
     "params": {
      "isPredictionTarget": false,
      "observationIndex": 0
     }
    },
    {
     "id": "comp11",
     "type": "observation",
     "position": {
      "x": 5,
      "y": 5
     },
     "params": {
      "isPredictionTarget": false,
      "observationIndex": 1
     }
    },
    {
     "id": "comp15",
     "type": "filter",
     "position": {
      "x": 4,
      "y": 4
     },
     "params": {
      "targetColor": "red",
      "inputSide": "up",
      "matchOutputSide": "left",
      "nonMatchOutputSide": "right",
      "plex": false,
      "speed": 1
     }
    }
   ],
   "connections": [
    {
     "from": "comp1",
     "to": "arm1"
    },
    {
     "from": "arm1",
     "to": "comp2"
    },
    {
     "from": "comp8",
     "to": "comp11"
    },
    {
     "from": "comp9",
     "to": "comp10"
    },
    {
     "from": "comp2",
     "to": "comp15"
    },
    {
     "from": "comp15",
     "to": "comp9"
    },
    {
     "from": "comp15",
     "to": "comp8"
    }
   ],
   "dgpScript": "\nsack(\"comp1\", {red: 50, blue: 30, green: 20});\n\nconst arm1 = arm();\n\nschedule({\n  arm1: [0]\n});\n\npredict(\"dist\");\n\nmontecarlo(1000);",
   "dgpResult": {
    "sacks": {
     "comp1": {
      "label": "comp1",
      "contents": {
       "red": 50,
       "blue": 30,
       "green": 20
      },
      "mode": "finite"
     }
    },
    "arms": {
     "arm1": {
      "id": "arm1",
      "varName": "arm1"
     }
    },
    "schedule": [
     {
      "armId": "arm1",
      "armVarName": "arm1",
      "time": 0
     }
    ],
    "questionText": "",
    "prediction": {
     "target": null,
     "what": "dist"
    },
    "buckets": null,
    "monteCarloSamples": 1000,
    "showFullDistribution": false,
    "fineGrainedDisplay": null,
    "disableBranching": false,
    "ballCount": 1
   },
   "samplingSchedule": [
    {
     "armId": "arm1",
     "armVarName": "arm1",
     "time": 0
    }
   ],
   "correctDistribution": {
    "A": 0.5,
    "B": 0.5
   },
   "intendedModel": "",
   "simulation": {
    "ballProductionInterval": 3000,
    "ballSpeed": 1,
    "ballsToSpawn": 1,
    "seed": 1550565845
   }
  }
 },
 {
  "title": "Plexiglass hides a ball’s colour",
  "body": "Behind plexiglass you can still see the belt and that a ball is on it — but not its colour. The ball shows gray with a “?”. You’d have to work out the colours from how the factory behaves downstream.",
  "level": {
   "meta": {
    "id": "tut-plex",
    "title": "tut-plex"
   },
   "grid": {
    "width": 9,
    "height": 8
   },
   "veiledTiles": [],
   "components": [
    {
     "id": "sack",
     "type": "sack",
     "position": {
      "x": 4,
      "y": 1
     },
     "params": {
      "label": "sack",
      "showContents": true,
      "contents": {
       "red": 50,
       "blue": 30,
       "green": 20
      }
     }
    },
    {
     "id": "arm",
     "type": "arm",
     "position": {
      "x": 4,
      "y": 2
     },
     "params": {
      "assignedSackId": null,
      "outputConveyorId": null,
      "varName": "arm",
      "id": "arm",
      "label": "arm",
      "drawCount": 1,
      "plex": true
     }
    },
    {
     "id": "c1",
     "type": "conveyor",
     "position": {
      "x": 4,
      "y": 3
     },
     "params": {
      "direction": "down",
      "speed": 1,
      "plex": true
     }
    },
    {
     "id": "c2",
     "type": "conveyor",
     "position": {
      "x": 4,
      "y": 4
     },
     "params": {
      "direction": "down",
      "speed": 1,
      "plex": true
     }
    },
    {
     "id": "obs",
     "type": "observation",
     "position": {
      "x": 4,
      "y": 5
     },
     "params": {
      "isPredictionTarget": true,
      "observationIndex": 0,
      "plex": true
     }
    }
   ],
   "connections": [
    {
     "from": "sack",
     "to": "arm"
    },
    {
     "from": "arm",
     "to": "c1"
    },
    {
     "from": "c1",
     "to": "c2"
    },
    {
     "from": "c2",
     "to": "obs"
    }
   ],
   "samplingSchedule": [
    {
     "armId": "arm",
     "armVarName": "arm",
     "time": 0
    }
   ],
   "simulation": {
    "ballProductionInterval": 3000,
    "ballSpeed": 1,
    "ballsToSpawn": 1,
    "seed": 12345
   }
  }
 },
 {
  "title": "Hidden parts you must infer",
  "body": "And sometimes a whole part of the factory is hidden — you see balls go in and where they come out, but not the mechanism in between. Together with the other players, you infer it from those inputs and outputs. That is the game.",
  "level": {
   "meta": {
    "id": "level-13",
    "title": "Level 13",
    "description": "Testing from editor",
    "bettingConfig": {
     "granularity": 10
    }
   },
   "grid": {
    "width": 10,
    "height": 8
   },
   "veiledTiles": [
    {
     "x": 4,
     "y": 4
    }
   ],
   "components": [
    {
     "id": "comp1",
     "type": "sack",
     "position": {
      "x": 4,
      "y": 1
     },
     "params": {
      "label": "comp1",
      "showContents": true,
      "contents": {
       "red": 50,
       "blue": 30,
       "green": 20
      }
     }
    },
    {
     "id": "comp2",
     "type": "conveyor",
     "position": {
      "x": 4,
      "y": 3
     },
     "params": {
      "direction": "down",
      "speed": 1,
      "plex": false
     }
    },
    {
     "id": "arm1",
     "type": "arm",
     "position": {
      "x": 4,
      "y": 2
     },
     "params": {
      "assignedSackId": null,
      "outputConveyorId": null,
      "varName": "arm1",
      "id": "arm1",
      "label": "arm1",
      "drawCount": 1
     }
    },
    {
     "id": "comp8",
     "type": "conveyor-turn",
     "position": {
      "x": 5,
      "y": 4
     },
     "params": {
      "turn": "right-to-down",
      "speed": 1,
      "plex": false
     }
    },
    {
     "id": "comp9",
     "type": "conveyor-turn",
     "position": {
      "x": 3,
      "y": 4
     },
     "params": {
      "turn": "left-to-down",
      "speed": 1,
      "plex": false
     }
    },
    {
     "id": "comp10",
     "type": "observation",
     "position": {
      "x": 3,
      "y": 5
     },
     "params": {
      "isPredictionTarget": false,
      "observationIndex": 0
     }
    },
    {
     "id": "comp11",
     "type": "observation",
     "position": {
      "x": 5,
      "y": 5
     },
     "params": {
      "isPredictionTarget": false,
      "observationIndex": 1
     }
    },
    {
     "id": "comp15",
     "type": "filter",
     "position": {
      "x": 4,
      "y": 4
     },
     "params": {
      "targetColor": "red",
      "inputSide": "up",
      "matchOutputSide": "left",
      "nonMatchOutputSide": "right",
      "plex": false,
      "speed": 1
     }
    }
   ],
   "connections": [
    {
     "from": "comp1",
     "to": "arm1"
    },
    {
     "from": "arm1",
     "to": "comp2"
    },
    {
     "from": "comp8",
     "to": "comp11"
    },
    {
     "from": "comp9",
     "to": "comp10"
    },
    {
     "from": "comp2",
     "to": "comp15"
    },
    {
     "from": "comp15",
     "to": "comp9"
    },
    {
     "from": "comp15",
     "to": "comp8"
    }
   ],
   "dgpScript": "\nsack(\"comp1\", {red: 50, blue: 30, green: 20});\n\nconst arm1 = arm();\n\nschedule({\n  arm1: [0]\n});\n\npredict(\"dist\");\n\nmontecarlo(1000);",
   "dgpResult": {
    "sacks": {
     "comp1": {
      "label": "comp1",
      "contents": {
       "red": 50,
       "blue": 30,
       "green": 20
      },
      "mode": "finite"
     }
    },
    "arms": {
     "arm1": {
      "id": "arm1",
      "varName": "arm1"
     }
    },
    "schedule": [
     {
      "armId": "arm1",
      "armVarName": "arm1",
      "time": 0
     }
    ],
    "questionText": "",
    "prediction": {
     "target": null,
     "what": "dist"
    },
    "buckets": null,
    "monteCarloSamples": 1000,
    "showFullDistribution": false,
    "fineGrainedDisplay": null,
    "disableBranching": false,
    "ballCount": 1
   },
   "samplingSchedule": [
    {
     "armId": "arm1",
     "armVarName": "arm1",
     "time": 0
    }
   ],
   "correctDistribution": {
    "A": 0.5,
    "B": 0.5
   },
   "intendedModel": "",
   "simulation": {
    "ballProductionInterval": 3000,
    "ballSpeed": 1,
    "ballsToSpawn": 1,
    "seed": 1550565845
   }
  }
 }
];
